name: dart_ipfs_client
description: A client library for the IPFS HTTP API.
version: 0.0.1
homepage: https://github.com/ngngardner/dart_ipfs_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  chopper: ^4.0.1
  json_annotation: ^4.1.0
  json_serializable: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  chopper_generator: ^4.0.1
  logging: ^1.0.1
  pedantic: ^1.11.1
  test: ^1.17.12
